### ISSUE TITLE
Disable "calculatePlayerVisibilityByFriendly"

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/arc_misc#120]
https://community.bistudio.com/wiki/calculatePlayerVisibilityByFriendly

Might improve performance ever so slightly.

**Comment by BorderKeeper** [comment]
It says it's false by default or is turning it on gonna increase performance?

**Comment by Freddo3000** [comment]
> 
> 
> It says it's false by default or is turning it on gonna increase performance?

Missed that it was default to off, was planning on turning it off similar to `disableRemoteSensors`
