### ISSUE TITLE
spotlight connectToServer command must use IP

### ISSUE THREAD

**Issue by Drofseh** [ARCOMM/arc_misc#162]
This must be IP, cannot be URL
https://community.bistudio.com/wiki/connectToServer

https://github.com/ARCOMM/arc_misc/blob/b9af9f7757f0899accc970f93f0f8e1427511d32/addons/main/CfgMainMenuSpotlight.hpp#L28

**Comment by Freddo3000** [comment]
https://feedback.bistudio.com/T159809
