### ISSUE TITLE
Add additional TMF autotests

### ISSUE THREAD

**Issue by Freddo3000** [ARCOMM/arc_misc#32]
- [ ] Check if AI disabled
- [ ] Check if HCs present

**Comment by BorderKeeper** [comment]
If possible these would also be good to check 
Unit having no radios 
Group callsign not matching group marker
Side briefing present despite no player unit on that side and vice versa 
No language assigned to side

**Comment by Freddo3000** [comment]
Unit having no radios is difficult to check, as it might be intentional. I have however set it up so it will make sure that players have a radio network and babel language assigned in the next TMF update.
