### ISSUE TITLE
Tweak weapon attachments for USMC loadouts

### ISSUE THREAD

**Issue by oileo** [ARCOMM/arc_misc#90]
The loadout (can't recall the name, main rifle is M16) has randomized attachments which aren't compatible with some weapons. Currently known examples are M16GLs, which become unusable with at least some sights, since it completely blocks the leaf sights when trying to fire grenades, and M249 having floating or clipping attachments. Examples below:

![20200815213435_1](https://user-images.githubusercontent.com/73077925/100615939-1d9be900-32f7-11eb-801f-974b5b7670eb.jpg)

![20201128183720_1](https://user-images.githubusercontent.com/73077925/100615974-2bea0500-32f7-11eb-99bf-3a73f918a328.jpg)

Both these examples happened this Saturday during Scot's _Going Coastal_, but first picture is from another op.

**Comment by AChesheireCat** [comment]
https://github.com/ARCOMM/arc_misc/pull/91

Hopefully this'll fix the issue :D I also did some other QoL stuff for the loadout considering it was one of my first ones I made.

**Comment by AChesheireCat** [comment]
Just merged the loadout fix that will resolve this. :D
